analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3472958,"name"\:"First Project","teamId"\:3458729,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3494705,"sampleProject"\:false,"autoIntegrate"\:false,"accountId"\:null}
analytics.team={"id"\:3458729,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
