<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Search</name>
   <tag></tag>
   <elementGuidId>fa3895e8-822b-49b6-bc40-64f10545149f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#created-by-me #search-table</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'created-by-me']//*[@id = 'search-table']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=textbox[name=&quot;Search&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0af92514-eea9-4231-b6e2-bfebe03137b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>ae0247e7-0705-4b05-ac63-a951d69a8eb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>a250c81c-fc26-42db-9e13-08b7d5d64c89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>71daf7f6-e50f-491e-bf4f-4807bcfc6e5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search-table</value>
      <webElementGuid>8f2c4ebb-6c05-439d-a506-4d64c6385c46</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-bd80b86c5bbf32e07a36a4bd9e1f4eb6</value>
      <webElementGuid>9dbbc2d3-8002-4bf8-b8a3-0e458eab58f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'created-by-me']//*[@id = 'search-table']</value>
      <webElementGuid>acc3c978-035c-433c-be9a-3df26cb1b0ed</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'created-by-me']//*[@id = 'search-table']</value>
      <webElementGuid>7078604d-6da4-404d-83ee-0124693a5b03</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @placeholder = 'Search' and @id = 'search-table']</value>
      <webElementGuid>2cec47b0-ba32-4ca7-8a65-154a0cda9eea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
