<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_message-dismiss</name>
   <tag></tag>
   <elementGuidId>40f99f63-3d71-4361-a416-1f44140d203d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#message-dismiss</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'message-dismiss']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;OK&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e12f71d8-a638-42dd-8e50-dc2a4f0f0c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>ff9e2b5c-b30d-461a-b3d2-7cc6894a7858</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>message-dismiss</value>
      <webElementGuid>d7afbf87-9a34-48c4-8192-1940cc493409</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn green</value>
      <webElementGuid>f542f10a-b88b-4c20-b8ea-d3226b2db1a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>e0075f45-9eec-42a1-a0a8-b9a0c62bbec3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d29341502308101fe7595a809b600dd6</value>
      <webElementGuid>7ffcc42b-dd09-4190-a1d5-73b1431ef66d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'message-dismiss']</value>
      <webElementGuid>0e538b74-7edc-4083-b727-3aaeb912845d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'message-dismiss']</value>
      <webElementGuid>ddc653e6-490a-4b55-9f1f-5139180668f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'message-dismiss' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>eee7b2b5-682d-4c9e-a5b9-4df789a0cc08</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
