<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_To mention a user or role, type  in fr</name>
   <tag></tag>
   <elementGuidId>c63a170a-f4da-4348-aa2b-602571b4378c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#remark-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'remark-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;To mention a user or role, type @ in front of name &amp; select.&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>722d3695-9575-4065-b4ed-59e149c4a84e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>7e33274e-26d7-4213-8cc0-fbbd0e3dad6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b463a5d3-7a7b-4ece-9818-c21b69292ed0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>remark-text</value>
      <webElementGuid>14799b62-6e9d-46e6-9bc6-2c3c36fbd250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>list</name>
      <type>Main</type>
      <value>users</value>
      <webElementGuid>3048fac9-c88a-4dc7-bf46-47d47f31336c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>comment</value>
      <webElementGuid>b8f7844d-556a-42f7-8f83-c30df7d66568</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>7000</value>
      <webElementGuid>db8e2a45-662c-4598-8e72-654a8cc22d89</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>3afdcac4-ffc1-418e-b677-3cad0d00b6c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>To mention a user or role, type @ in front of name &amp; select.</value>
      <webElementGuid>73f2b666-70eb-45c1-b617-518cd8c60d98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a06e693590fd00f95e6bcf1003571335</value>
      <webElementGuid>e5ed968b-2714-45d1-b83c-2ba3792e7431</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'remark-text']</value>
      <webElementGuid>ac1dd5ce-419d-48b3-8f8c-dc63da393031</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'remark-text']</value>
      <webElementGuid>abcd26d8-46d4-4929-acb2-bfde37f169ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'remark-text' and @name = 'comment' and @placeholder = 'To mention a user or role, type @ in front of name &amp; select.']</value>
      <webElementGuid>48383a31-518e-4bf2-8c56-9ecd5f779731</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
