<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_message-dismiss</name>
   <tag></tag>
   <elementGuidId>450e8101-c4dc-4469-9261-699b784f04ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#message-dismiss</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'message-dismiss']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;OK&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>a45ce19d-4d47-4841-91eb-b1a86a2509dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>26aef3bf-cae3-42fd-822b-46370dda35c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>message-dismiss</value>
      <webElementGuid>b113d9d4-9b71-447f-9127-421e3296da6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn green</value>
      <webElementGuid>4f149f95-7615-47a4-a996-2eb04f34ac18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>e032706b-053d-48d0-8461-0479ce41e97d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d29341502308101fe7595a809b600dd6</value>
      <webElementGuid>a4e44212-ff09-40f4-b37e-c9750a0df89c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'message-dismiss']</value>
      <webElementGuid>ce5467db-3e5a-426e-a637-689a903c5d09</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'message-dismiss']</value>
      <webElementGuid>2da766ca-22be-4aac-a997-4f3775a14c18</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'message-dismiss' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>f015ffe9-ffac-4a23-a18e-6371ed2ffd93</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
