<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_To mention a user or role, type  in fr</name>
   <tag></tag>
   <elementGuidId>1f79f423-66c0-4a0a-8082-e794b2f5c5f5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#remark-text</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'remark-text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;To mention a user or role, type @ in front of name &amp; select.&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>304f6f40-0d02-4289-a3cc-425b1639cf62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>db2fec40-119a-4682-a7cd-64cf12be627f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>0c5265bb-e3d0-4348-bd19-503a7b6d2af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>remark-text</value>
      <webElementGuid>d663f538-0ee4-448d-acab-c3cd07726ade</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>list</name>
      <type>Main</type>
      <value>users</value>
      <webElementGuid>47b9ab9f-0de7-4330-864d-89bdc93b19ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>comment</value>
      <webElementGuid>3538bc6b-2864-4cea-8b66-5512e6aece26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>7000</value>
      <webElementGuid>9b909d05-1adb-439a-860c-3c3e3d7da0c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>9b55d74f-0bc5-4f1d-9bfb-e9abe92b320b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>To mention a user or role, type @ in front of name &amp; select.</value>
      <webElementGuid>1354f421-8a11-466c-a45c-6d78d062ce50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a06e693590fd00f95e6bcf1003571335</value>
      <webElementGuid>d7850d98-eb60-4b6f-8573-93683ea2837a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'remark-text']</value>
      <webElementGuid>7bd55040-1074-43ee-a302-ef348d6ba2a3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'remark-text']</value>
      <webElementGuid>9590caef-30e0-421a-b85e-06db15d11510</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'remark-text' and @name = 'comment' and @placeholder = 'To mention a user or role, type @ in front of name &amp; select.']</value>
      <webElementGuid>b667b97b-fd94-4b82-afb8-7d494dddbdc2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
