<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_comment-closeSignModal</name>
   <tag></tag>
   <elementGuidId>24ae2f04-563c-4762-8e17-f6cbb5587104</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'comment-closeSignModal']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#comment-closeSignModal</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;×&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>444ae146-8c81-4b32-b689-c868c5a59edb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>closeSignModal</value>
      <webElementGuid>58792500-3dc7-4b94-a27c-ab1a521c39f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>comment-closeSignModal</value>
      <webElementGuid>4e559cd1-60a9-4017-bba6-ffd863d2d5fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>×</value>
      <webElementGuid>b15347cd-1753-44de-9c68-1e4624f2c081</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-862559d4201adc3ba5fb0cc9d6940d37</value>
      <webElementGuid>b5a212b2-35c6-4a63-9ba9-542567e3db14</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'comment-closeSignModal']</value>
      <webElementGuid>7183a716-194f-48e1-a113-bb2158ac7d84</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'comment-closeSignModal']</value>
      <webElementGuid>112590b9-dc2c-4305-a123-adfeb5976b6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'comment-closeSignModal' and (text() = '×' or . = '×')]</value>
      <webElementGuid>ca1c2b38-884f-4986-892d-2ebae3c69c99</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
