<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_message-dismiss</name>
   <tag></tag>
   <elementGuidId>9940def8-be77-4434-84d3-223ec783a9b5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#message-dismiss</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'message-dismiss']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;OK&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>729b0cc1-3cc8-4e75-98e7-8ea1eae44074</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-dismiss</name>
      <type>Main</type>
      <value>modal</value>
      <webElementGuid>61651a26-2b7a-41aa-82eb-49d3603c28c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>message-dismiss</value>
      <webElementGuid>a7ccdcd4-af67-47b2-9cf3-60d353703521</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>btn red</value>
      <webElementGuid>54e11b9b-4432-4225-a459-5e02ef845a9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>OK</value>
      <webElementGuid>2bd2acf1-b086-4b39-a8af-a27ea5542321</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-d29341502308101fe7595a809b600dd6</value>
      <webElementGuid>c77edb04-64a1-471a-9957-1bc0fbe08e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'message-dismiss']</value>
      <webElementGuid>9f1445ad-181e-4b44-adac-36f57d2eb7f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'message-dismiss']</value>
      <webElementGuid>c924091f-6e07-4387-899b-a83343b166dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@id = 'message-dismiss' and (text() = 'OK' or . = 'OK')]</value>
      <webElementGuid>63337458-9692-4e64-b641-5b2a00b7083d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
