<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_completed</name>
   <tag></tag>
   <elementGuidId>1003e579-8c8f-48f4-a4f8-790a8c41bfba</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[title=&quot;completed&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@title = 'completed']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[title=&quot;completed&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>764e87aa-dc0b-403a-bfad-3ad75ce50004</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-6 w-14  border-r-[0.5px] border-r-black p-1  flex items-center justify-center gap-1 cursor-pointer</value>
      <webElementGuid>4336c7f1-eb17-4b42-babf-be2eb1dee6c8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>completed</value>
      <webElementGuid>644d73d3-6964-4a7c-9e76-64f24720f4fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> OK</value>
      <webElementGuid>4059fc98-a179-4544-98e0-2eb2f8ed298e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-496614497f1859c7513f433885708f3b</value>
      <webElementGuid>44fd5559-06b5-44a0-91b4-edc659d7c334</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@title = 'completed']</value>
      <webElementGuid>f3ef916c-e32e-495f-bd05-a08c2f84b264</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Work Order  View- Workforce Manager/iframe_esign-widget</value>
      <webElementGuid>3b80dfe9-472b-4b74-a341-a83119e531e6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@title = 'completed']</value>
      <webElementGuid>ba4c4bb7-6905-4f5b-a738-313b741351cc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@title = 'completed' and (text() = ' OK' or . = ' OK')]</value>
      <webElementGuid>70b03c91-325b-4195-a8c0-e3c8c347b10d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
