<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe__esign-widget</name>
   <tag></tag>
   <elementGuidId>a8e837c2-9265-4c4b-ab78-72cb8b6848f4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#esign-widget</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='esign-widget']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;esign-widget&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>5f252167-4b05-43c6-9af3-37ca275b6bb3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://govtest.convergenceondemand.com/esign/ecms-sign</value>
      <webElementGuid>069dafac-268b-4560-a081-57457008c4bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>esign-widget</value>
      <webElementGuid>dd37db69-f280-4514-a034-8f4c993aa18e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>esign-widget</value>
      <webElementGuid>5fa073b4-5e48-45cd-95b0-9e59fa304869</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>213e7b51-7da1-4a4f-9732-aff164332187</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2e28d720-1e97-41ae-862b-70caaf548b51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;esign-widget&quot;)</value>
      <webElementGuid>5336f3d4-95e8-4f6b-8bad-1d755d303e19</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='esign-widget']</value>
      <webElementGuid>15a331ed-dfad-43ff-bd1c-35fa5af0daf0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>0964485e-a713-4f65-b08c-6d8a98044946</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://govtest.convergenceondemand.com/esign/ecms-sign' and @id = 'esign-widget' and @name = 'esign-widget']</value>
      <webElementGuid>4f45f8b5-d45d-48ef-aecf-8ebf299872bb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
