<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_esign-widget</name>
   <tag></tag>
   <elementGuidId>dca4fe6b-2900-4972-856f-ea7e7af3ca4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#esign-widget</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'esign-widget']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;esign-widget&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>27170938-dbd9-434d-98ba-a5021ec47f62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://govtest.convergenceondemand.com/esign/ecms-sign</value>
      <webElementGuid>c476ba4f-f61a-459d-853f-a2ff91e2000e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>esign-widget</value>
      <webElementGuid>829cd4a3-cd2e-417d-a30f-a0876f322675</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>esign-widget</value>
      <webElementGuid>98a54f03-418c-41f0-86eb-012bdd5874d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>92019842-c68c-4dde-a704-af8c8074b9e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>352195f8-be51-4f70-87a1-a518e76d6e8d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-91f54e20e1f3d3fac2787a22b0e94613</value>
      <webElementGuid>c20cec2f-5ca7-4113-b0a5-ba74f7c95298</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'esign-widget']</value>
      <webElementGuid>dcaf0469-82d1-4757-b9c7-9ad83ea2238c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[contains(@id,'esign')]</value>
      <webElementGuid>682cda01-c6d1-4509-84ac-a4ec2c3a6a77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://govtest.convergenceondemand.com/esign/ecms-sign' and @id = 'esign-widget' and @name = 'esign-widget']</value>
      <webElementGuid>91144721-8661-49ca-9343-b4e67fb81741</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
