<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_cde-widget</name>
   <tag></tag>
   <elementGuidId>58b56c61-8244-4260-aba5-6331eb97917e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cde-widget</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'cde-widget']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;cde-widget&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>e5673a17-3b1f-460a-b5f1-a6ba854898c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://govtest.convergenceondemand.com/cde/ecms-cde</value>
      <webElementGuid>1bf1f41a-bc4b-4072-bca8-432f0073534b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cde-widget</value>
      <webElementGuid>6c6d6a02-401b-4082-809f-44f5797aed36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cde-widget</value>
      <webElementGuid>396da492-8ccf-4825-99cc-c1a19fae14e7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>241bc502-fae0-4464-85b7-aeeb87512a04</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>4fda9761-93e1-454a-b568-2e0766911351</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-7f794dca172a3c8d0763ed83bc5d9711</value>
      <webElementGuid>109deabf-069c-40ef-b247-bb4003f59ab7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'cde-widget']</value>
      <webElementGuid>f0b6cbd7-60ab-4fbb-a0b8-f6b77153212b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'cde-widget']</value>
      <webElementGuid>d1cd6ba1-a86f-4e9d-be4c-51280bf4c8f8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://govtest.convergenceondemand.com/cde/ecms-cde' and @id = 'cde-widget' and @name = 'cde-widget']</value>
      <webElementGuid>f6926762-778f-4bf9-8906-bc8ba34bb961</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
