<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_From Device_1</name>
   <tag></tag>
   <elementGuidId>1871394b-5342-4a7e-9bc3-81eb0fb2a96d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#file_upload</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'file_upload']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Upload File&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0fc1757-db62-4b72-bdb4-33ab36c67619</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>1283ae5a-8b64-414f-8c2e-3efe1e8a3c05</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>handleWorkOrderAttach(this.id)</value>
      <webElementGuid>9a87871b-c181-41c8-8846-50edd2f9ad86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>file_upload</value>
      <webElementGuid>4c07e526-333d-46ce-aa49-eae1fb5b2f03</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-18e7b3886de2606066c70d2110aeb4ed</value>
      <webElementGuid>dc621e2d-b694-4910-958c-c664215e7833</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'file_upload']</value>
      <webElementGuid>8bf25478-6654-4b3e-b1fb-a55dde298f82</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'file_upload']</value>
      <webElementGuid>03477cd2-0709-47ce-addc-e27565c00f05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'file_upload']</value>
      <webElementGuid>50a39600-7c2e-4066-bb16-acc9e745c441</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
