<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_checkbox</name>
   <tag></tag>
   <elementGuidId>56001bd8-a2e8-48cc-b8f3-99dce7e839db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.antialiased.h-max[data-value=&quot;My-Documents&quot;] #checkbox</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' antialiased ') and contains(concat(' ', normalize-space(@class), ' '), ' h-max ') and (@data-value = 'My-Documents')]//*[@id = 'checkbox']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>cc9c4eaf-61c7-48c4-b8d4-076d43d9420a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>e83a17cc-9943-459d-a255-2fba1e57dff5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>peer relative appearance-none w-5 h-5 border rounded-md border-blue-gray-200 cursor-pointer transition-all before:content[''] before:block before:bg-blue-gray-500 before:w-12 before:h-12 before:rounded-full before:absolute before:top-2/4 before:left-2/4 before:-translate-y-2/4 before:-translate-x-2/4 before:opacity-0 hover:before:opacity-10 before:transition-opacity checked:bg-teal-500 checked:border-teal-500 checked:before:bg-teal-500</value>
      <webElementGuid>97a254d7-12d7-402b-b61d-4270bba67bdc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>233cb47d-ee88-4a97-877c-c509a23d435f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-32ffa7929761fd8d161677db0d78b64a</value>
      <webElementGuid>497320d4-73ba-4152-b97f-29840921bfe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' antialiased ') and contains(concat(' ', normalize-space(@class), ' '), ' h-max ') and (@data-value = 'My-Documents')]//*[@id = 'checkbox']</value>
      <webElementGuid>48fd1d6a-3292-4b7b-a26f-c15d0b7397f6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Work Order  View- Workforce Manager/iframe_cde-widget</value>
      <webElementGuid>778a11e8-0a08-4643-9535-992537806e97</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' antialiased ') and contains(concat(' ', normalize-space(@class), ' '), ' h-max ') and (@data-value = 'My-Documents')]//*[@id = 'checkbox']</value>
      <webElementGuid>7f674b5a-7c78-4b83-b045-7fe4ebd39a39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'checkbox']</value>
      <webElementGuid>d7459607-2dba-4d04-b46c-10e9ce05d7db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
