<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_From Device</name>
   <tag></tag>
   <elementGuidId>39b2eb38-9569-49f5-97b3-dd755452e32b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#file_upload</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'file_upload']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Upload File&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>eb426438-8303-4f49-a67c-b2fe3c9ccde1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>b0e31bb4-2069-42ec-9aa4-e23a30104e3a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>handleWorkOrderAttach(this.id)</value>
      <webElementGuid>118cde73-a94c-4d85-9b68-3aa76ce25536</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>file_upload</value>
      <webElementGuid>08a0f9a7-5634-4392-8c57-349b17cb3a88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-18e7b3886de2606066c70d2110aeb4ed</value>
      <webElementGuid>76cf768e-b6cd-4440-8a31-e99645b3b53d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'file_upload']</value>
      <webElementGuid>25506c90-42e3-4787-8014-5656dff7705b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'file_upload']</value>
      <webElementGuid>a9c7e317-1c0a-406d-b862-d866094b8a78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'file_upload']</value>
      <webElementGuid>28411359-dc1a-4105-b38e-fae54404a553</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
