<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Save</name>
   <tag></tag>
   <elementGuidId>efe5b4a6-371b-4de8-b8ab-a7beec97a296</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.undefined.bg-green-primary.rounded-full.false .text-white</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' undefined ') and contains(concat(' ', normalize-space(@class), ' '), ' bg-green-primary ') and contains(concat(' ', normalize-space(@class), ' '), ' rounded-full ') and contains(concat(' ', normalize-space(@class), ' '), ' false ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' text-white ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Save&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>0c6fd3ed-b56b-42d1-a28b-93c81cd590df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>text-[11px] text-white </value>
      <webElementGuid>69a41a6c-360d-4bc6-9789-1d891cec656b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Save</value>
      <webElementGuid>2da6a41b-2928-4cba-8a06-8bdb3113da90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8b58732380a9c30464410c123e05e5be</value>
      <webElementGuid>d989e8d2-52a4-4cf1-be36-ec7f3f6c335d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' undefined ') and contains(concat(' ', normalize-space(@class), ' '), ' bg-green-primary ') and contains(concat(' ', normalize-space(@class), ' '), ' rounded-full ') and contains(concat(' ', normalize-space(@class), ' '), ' false ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' text-white ')]</value>
      <webElementGuid>f5100df5-915a-45d2-961a-3bd839df1e23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_Work Order  View- Workforce Manager/iframe_esign-widget</value>
      <webElementGuid>5647f139-d724-4a88-a94b-5db9cc53df7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' undefined ') and contains(concat(' ', normalize-space(@class), ' '), ' bg-green-primary ') and contains(concat(' ', normalize-space(@class), ' '), ' rounded-full ') and contains(concat(' ', normalize-space(@class), ' '), ' false ')]//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' text-white ')]</value>
      <webElementGuid>409f6b7f-d0e2-43b6-8261-f1243e1e98cd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'Save' or . = 'Save')]</value>
      <webElementGuid>b2c5d562-be53-469c-b979-2e2b80a3dc51</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
