<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_svg</name>
   <tag></tag>
   <elementGuidId>dd33a888-3785-4ab1-96e9-cff185c4eebd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>tr:nth-child(1) span:nth-child(3) [fill=&quot;none&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(name() = 'tr') and (position() = 1)]//*[(name() = 'span') and (position() = 3)]//*[@fill = 'none']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[(name() = 'tr') and (position() = 1)]//*[(name() = 'span') and (position() = 3)]//*[@fill = 'none']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=row[name=&quot;PAST.pdf 2026-05-25 11:53:09 2026-05-25 12:05:27 api support View | Download | Sign | file upload icon | Delete |&quot;i] >> internal:attr=[title=&quot;Sign&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>241c2390-7446-4d38-a5bb-fa82fb5e4e9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>f52d6731-385e-403d-9453-3ccdb0e469b5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>17</value>
      <webElementGuid>576140e2-d985-45ab-ac19-23057c34d37c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 17 17</value>
      <webElementGuid>1726cb18-38b4-4f74-8365-bc444e07ecb6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>fb49d003-e8cb-4dc0-a1bc-b43235da98e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>15e39846-cbfe-4779-b141-6837f1781f6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-ca811dffc4a4c51d97304c32f8c18bd3</value>
      <webElementGuid>222ee673-334b-4ec9-980b-38e855323881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(name() = 'tr') and (position() = 1)]//*[(name() = 'span') and (position() = 3)]//*[@fill = 'none']</value>
      <webElementGuid>adf85771-8609-44ee-ab68-f09bd61a68cf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(name() = 'tr') and (position() = 1)]//*[(name() = 'span') and (position() = 3)]//*[@fill = 'none']</value>
      <webElementGuid>4e85dc19-75d1-4762-87cd-b13005f2c808</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(name() = 'tr') and (position() = 1)]//*[(name() = 'span') and (position() = 1)]//*[@fill = 'none']</value>
      <webElementGuid>bc6d211a-7a71-418b-a5ad-8e44242b65a5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
