<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_To mention a user or role, type  in fr</name>
   <tag></tag>
   <elementGuidId>d123f129-bbd3-429b-bd8b-04455945f65e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'remark-text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#remark-text</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@id = 'remark-text' and @name = 'comment' and @placeholder = 'To mention a user or role, type @ in front of name &amp; select.']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;To mention a user or role, type @ in front of name &amp; select.&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>1f5a2ec4-a716-4330-a193-8c4fc01bc02b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>rows</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>8412e3ab-3ebd-4151-ab55-2abf9d24889f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>afcb8bd1-0625-47e6-8d70-d7042d389cad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>remark-text</value>
      <webElementGuid>269b2cce-9534-4df2-b52f-f887686ef93b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>list</name>
      <type>Main</type>
      <value>users</value>
      <webElementGuid>d535b08e-8ab0-4008-aeeb-fcf71ef67db4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>comment</value>
      <webElementGuid>49d8d541-d478-46c0-b329-1827bfd93e3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>7000</value>
      <webElementGuid>792818e2-8bb7-4d39-9bba-4a293325c65a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>required</value>
      <webElementGuid>ef091fb2-2a31-4fd3-bf5e-244834e62504</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>To mention a user or role, type @ in front of name &amp; select.</value>
      <webElementGuid>e880961e-45f8-404e-8336-8c4997212c1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-a06e693590fd00f95e6bcf1003571335</value>
      <webElementGuid>cb8c6aad-f30f-491c-85a3-e458a15d24eb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'remark-text']</value>
      <webElementGuid>629a069a-ca2e-44a7-aeb2-d09b319d36fd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'remark-text']</value>
      <webElementGuid>bd1e534a-b387-4e61-b36a-09be3a1108b2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@id = 'remark-text' and @name = 'comment' and @placeholder = 'To mention a user or role, type @ in front of name &amp; select.']</value>
      <webElementGuid>eaa615d8-78f8-4aa4-8b3e-267f12ea8e1e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
