<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_cdeWidget</name>
   <tag></tag>
   <elementGuidId>30f50037-d9c1-4367-bddc-dd828b76b59e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cde-widget</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'cde-widget']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;cde-widget&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>7bc0251f-d304-4fad-bf3d-9496dd8db9cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://govtest.convergenceondemand.com/cde/ecms-cde</value>
      <webElementGuid>0adc33a9-f51d-403b-8532-fb721a204c74</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cde-widget</value>
      <webElementGuid>1f03f7a3-9a8f-4d49-ac1b-78acf2d39945</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cde-widget</value>
      <webElementGuid>58c426f7-bcb3-4d82-939e-8cac521c07fb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>ee9b87f9-6aad-498e-9592-adb0585842b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>7f283860-8492-4b77-80aa-c877d6e54642</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-7f794dca172a3c8d0763ed83bc5d9711</value>
      <webElementGuid>09f21214-313c-4a4f-a86d-4cb20007c374</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'cde-widget']</value>
      <webElementGuid>1664a188-fda1-4223-be65-866a48fc2119</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'cde-widget']</value>
      <webElementGuid>9ef9d016-c62e-4649-a130-1ceb0db22393</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://govtest.convergenceondemand.com/cde/ecms-cde' and @id = 'cde-widget' and @name = 'cde-widget']</value>
      <webElementGuid>20c720b9-34c9-4976-9284-8b645f504f00</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
