<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Login</name>
   <tag></tag>
   <elementGuidId>5b7777f9-8499-419a-b15b-ea642b77f72a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.rounded-xl</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' rounded-xl ')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'submit' and (text() = 'Login' or . = 'Login')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Login&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>f24a94b4-2215-44e7-9be6-d8f4225afa18</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>185cc09d-d47b-4848-9234-adb5814af8f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>h-12 bg-brand-green text-white rounded-xl mb-6 w-full disabled:bg-gray-300 disabled:text-gray-500 transition-all text-[18px]</value>
      <webElementGuid>71b5c087-00dd-4303-a3ca-de49c1fd7023</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>7751366d-c1b5-45b9-a41d-6e8b00b2d883</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-41d4d2858cec6960a4c1c669119c5a10</value>
      <webElementGuid>6ed48d64-4727-4129-a891-4344e704c2ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' rounded-xl ')]</value>
      <webElementGuid>1d72fdfc-6225-4142-8dd6-42a4cf50cea3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' rounded-xl ')]</value>
      <webElementGuid>fc60a1f7-725d-47f3-9683-a74d7a53f261</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>d011fc62-6bd4-4af3-af32-b789914c55ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
