<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ClosePopnup</name>
   <tag></tag>
   <elementGuidId>e95ab2f2-3ec7-4e94-adac-125cad67b9d7</elementGuidId>
   <imagePath>Screenshots/Targets/Page_1Gov/button_ClosePopnup.png</imagePath>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>IMAGE</key>
         <value>Screenshots/Targets/Page_1Gov/button_ClosePopnup.png</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Gov Drive'])[1]/following::*[name()='svg'][1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button >> nth=1</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>63d2497a-6930-4b16-abab-39dee5d25e6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>cad90b70-f93c-4d41-8af3-1cb5d6cde46b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>16b84056-9ead-4d14-8e43-7a6ffa9d0046</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>09387f7d-b0ba-4141-a5f7-19de9a94722e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 352 512</value>
      <webElementGuid>d8c99d2e-27b4-40a5-a606-e97545352c6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>8581e27a-63e9-4f28-a157-d02bea283878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>c7ef78a7-7578-4901-9931-8fbe0f2e06d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xmlns</name>
      <type>Main</type>
      <value>http://www.w3.org/2000/svg</value>
      <webElementGuid>da3dbd5e-a368-4888-8efd-d2ec30616f1d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;__variable_f367f3 min-h-screen antialiased&quot;]/div[@class=&quot;font-open-sans&quot;]/div[@class=&quot;min-h-screen bg-white&quot;]/div[@class=&quot;flex flex-col lg:grid lg:grid-cols-[15fr_67fr_21fr] gap-4 px-4 md:px-8 pt-20 min-h-screen bg-[#f1f3f4]&quot;]/main[@class=&quot;flex-1 overflow-y-auto scroll-smooth mt-4 mb-4 pt-8 pb-4 px-8 bg-white rounded-2xl&quot;]/div[@class=&quot;space-y-10&quot;]/div[@class=&quot;fixed inset-0 z-[1000] flex items-center justify-center p-4&quot;]/div[@class=&quot;relative bg-white rounded-3xl shadow-2xl overflow-hidden transition-all duration-300 max-w-md w-full&quot;]/button[@class=&quot;absolute top-4 right-4 w-8 h-8 flex items-center justify-center rounded-full hover:bg-gray-100 text-gray-400 transition-colors z-10&quot;]/svg[1]</value>
      <webElementGuid>2e7414bd-10a7-425d-9771-13e2fd19f234</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gov Drive'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>d716c957-36fe-4cc2-8124-0d7731f14b14</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='beta'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>c220eca0-c0c3-4ab2-bef9-20abe286fbba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Help us improve 1Gov services'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>976836c1-7a8c-4614-9814-b2ab34e4f84e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Later'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>cd4953a1-2713-40af-82df-8e96d2625c59</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
