<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_TEST AUTOMATION</name>
   <tag></tag>
   <elementGuidId>9d6a3b57-44cc-4ec8-8442-d8432f962c0c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>li:nth-child(114) [role=&quot;option&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@role='option'][.//span[normalize-space(text())='TEST AUTOMATION']]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'TEST AUTOMATION ' or . = 'TEST AUTOMATION ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=listbox >> internal:role=option[name=&quot;TEST AUTOMATION&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>cf5b5c91-a851-4e74-8b35-f5f4967a36db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>7e475d0b-dc94-4404-bacb-955e304d4507</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tokens</name>
      <type>Main</type>
      <value>null</value>
      <webElementGuid>e67ccab8-784e-4638-b2ec-49eb5cc1455e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>e5346728-fe6b-4987-8411-b365f80c8b7b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>ff311a67-58bb-437b-ae91-167b81d75e17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>e5d92d52-e27e-4d28-87b5-3fd202d42249</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>TEST AUTOMATION </value>
      <webElementGuid>02b252cf-76d6-44ce-985f-aaa2e70f9687</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-f34dcfbb7ce370f7f0c80a6a427a80a0</value>
      <webElementGuid>85a2ccda-4079-47e8-83bd-3220a80a63ff</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(name() = 'li') and (position() = 114)]//*[@role = 'option']</value>
      <webElementGuid>7b478f84-67de-4cca-8654-cfa79c5c8927</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(name() = 'li') and (position() = 114)]//*[@role = 'option']</value>
      <webElementGuid>02d4cfe3-4fcf-408b-b3ad-738f747db4c0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'TEST AUTOMATION ' or . = 'TEST AUTOMATION ')]</value>
      <webElementGuid>a2981f29-b214-472b-848c-06dbfc51c81f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(name() = 'li') and (position() = 110)]//*[@role = 'option']</value>
      <webElementGuid>6651b045-4629-4bf4-861b-513303990ebf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
