<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Task Title _</name>
   <tag></tag>
   <elementGuidId>f0e917b7-ac69-4eeb-9f1d-99e4622174d5</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'WorkOrder_summary']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#WorkOrder_summary</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'summary' and @id = 'WorkOrder_summary' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Task Title \n         \n        *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>16dc852a-b048-41f3-88a4-11711506c6ea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>f40d98c5-f0e5-4534-a4a4-aac5827e9e0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>5c416ce4-b406-4d2a-851b-5498cefaf651</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>5895dd71-ce23-4b2c-83e4-acb2d783377a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>summary</value>
      <webElementGuid>993a78de-f8d5-4b42-9382-e969daca5b78</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WorkOrder_summary</value>
      <webElementGuid>bb93b338-86db-491f-8721-5d693cfd442e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>053e5ead-73c7-4dab-adc5-c082dbdcc76a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3e1a3c8d-2f26-43ff-8ec4-57e867378098</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3a0df69f496e2c1369253b20a4fd6753</value>
      <webElementGuid>198318c2-d8f4-436d-97d9-ea1666f38386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'WorkOrder_summary']</value>
      <webElementGuid>4028d861-ec61-4e9d-b014-d437058fde40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'WorkOrder_summary']</value>
      <webElementGuid>d7a3d383-ff6a-4547-ba40-e16e1a504b68</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'summary' and @id = 'WorkOrder_summary' and @type = 'text']</value>
      <webElementGuid>f44507d9-c088-40d4-9471-d5216a5f924a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
