<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_form-upload_input</name>
   <tag></tag>
   <elementGuidId>a3210aef-4be6-4266-b236-0a81f76e9305</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#form-upload__input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'form-upload__input']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#form-upload__input</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9a21ca4c-ef4d-46ca-8a88-6ad78478efdb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>5ead103b-717a-4cc8-a842-cd7ef1e9b801</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-upload__input</value>
      <webElementGuid>f0472870-afa5-4145-b1c1-814cd401360f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form-upload__input</value>
      <webElementGuid>094dd0ca-fc7d-4a8c-8d60-ff1ee2028fe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.png, .gif, .jpg, .jpeg, .pdf, .txt, .doc, .xlm, .xls, .xlsx, .docx, .ppt</value>
      <webElementGuid>869b7442-687a-4446-ac96-599db55bb1c9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enctype</name>
      <type>Main</type>
      <value>multipart/form-data</value>
      <webElementGuid>d04f3cb2-ab99-45c7-8d58-596d970b5743</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-cdc69b107115bbe5395c81090ca8dfe2</value>
      <webElementGuid>ee297dec-df83-4b30-adcd-82b6fa8ba1c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'form-upload__input']</value>
      <webElementGuid>6adaff6d-6cd1-4f08-896b-81bd9f5a679f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'form-upload__input']</value>
      <webElementGuid>d0b1abfa-a40c-48b0-b45e-df22f56caa70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'form-upload__input']</value>
      <webElementGuid>9e075aec-a634-4744-a440-0056942fddc8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
