<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_should_assign_ticket</name>
   <tag></tag>
   <elementGuidId>9276152a-6db6-4eb8-a015-7d689e8ac400</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'should_assign_ticket']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#should_assign_ticket</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'checkbox' and @id = 'should_assign_ticket']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#should_assign_ticket</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>9b234dbd-ca41-4154-b471-179d12608446</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7c78910c-3575-4ef8-a2e5-1e011afd4250</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>should_assign_ticket</value>
      <webElementGuid>12421ff8-6a25-4206-8697-7a8b3e432501</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-31bd5608918ba8e914276ea5fbd3f6f0</value>
      <webElementGuid>d86a0796-52bb-44e4-8719-7f3419e72af5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'should_assign_ticket']</value>
      <webElementGuid>fa257152-fc97-442d-9725-1348d168ac5e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'should_assign_ticket']</value>
      <webElementGuid>b96f4de5-a1e5-4bb3-a32a-f5a7e805ce25</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'should_assign_ticket']</value>
      <webElementGuid>dbb6785e-5768-4b41-a617-3fe7a90b83ba</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
