<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_file_upload_input_1779184122</name>
   <tag></tag>
   <elementGuidId>180ea5f5-6433-49fa-8402-afe2d37d770a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.form-upload__input</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-upload__input ')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#file_upload__input_1779184122</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5f3fee5c-fb8d-4136-a9ad-361afd87f4f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>d6bf0090-41d3-4ce6-8800-b877c07264d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-upload__input</value>
      <webElementGuid>16fbf986-7c85-4cfa-9d42-64928fd63d90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>file_upload__input_1779184122</value>
      <webElementGuid>d1cc5316-70fb-43d8-8412-a268c280468b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.png, .gif, .jpg, .jpeg, .pdf, .txt, .doc, .xlm, .xls, .xlsx, .docx, .ppt</value>
      <webElementGuid>54ccc8d8-5276-4f12-b266-c5f11fcf820c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enctype</name>
      <type>Main</type>
      <value>multipart/form-data</value>
      <webElementGuid>af0aa586-19fc-4376-b59d-cab9dcf64ee2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0e6a9444365fed0c374fca3175bde69d</value>
      <webElementGuid>93b0c013-cd07-4c67-9aa4-62e16e04132b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-upload__input ')]</value>
      <webElementGuid>6bed8a3d-dac7-47d6-aa3d-31625b17cfbb</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' form-upload__input ')]</value>
      <webElementGuid>1220c346-25d6-457d-a4ad-df57853ccd9f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'file_upload__input_1779184122']</value>
      <webElementGuid>f5e3e11a-c01f-4135-8a12-5dbfde5ffcfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
