<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Description</name>
   <tag></tag>
   <elementGuidId>d1bd4ae3-47b9-4f14-8e8b-7a79df032c4c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#WorkOrder_description</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value>//*[@name = 'description' and @id = 'WorkOrder_description']</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'WorkOrder_description']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Description&quot;s</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>7af211ec-f174-4ba2-bbd0-65cc4aad7ac4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>row-forms</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>da6bcb68-078f-4e56-b02b-15f15fbf3ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>cols</name>
      <type>Main</type>
      <value>50</value>
      <webElementGuid>c088eab6-2988-451e-a6af-605f66cea92b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>3599dd43-dff1-425c-b2d0-66e3a2a8e842</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>description</value>
      <webElementGuid>db5f5e01-6f8c-4748-a488-9fad2f23935f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WorkOrder_description</value>
      <webElementGuid>95ed2a8d-ae80-4044-9fd8-334cc983c57a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-77d515dde6027d84dfec0c69cc81301b</value>
      <webElementGuid>4c96a75d-6b63-4ff5-8e40-74c935a406ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'WorkOrder_description']</value>
      <webElementGuid>16b5721d-0fb3-4349-b066-80aea2fd35b4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'WorkOrder_description']</value>
      <webElementGuid>63e4f0ec-c27e-491f-a323-031426c20914</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'description' and @id = 'WorkOrder_description']</value>
      <webElementGuid>1fddbd83-9e67-4acf-a8b6-689259b962db</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
