<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_QA</name>
   <tag></tag>
   <elementGuidId>10981c7b-d312-438e-b8f3-ce9b6e8bd417</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[(name() = 'li') and (position() = 112)]//*[@role = 'option']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li:nth-child(112) [role=&quot;option&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=listbox >> internal:role=option[name=&quot;QA&quot;s]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ed98dfa4-27b5-4d4c-bee4-e7e2c9a60ff7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>f58f8a3a-39ea-46e2-9dc9-76a80d88ee5c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tokens</name>
      <type>Main</type>
      <value>null</value>
      <webElementGuid>9071e4b8-7096-413c-928b-683137db3b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>10efe12b-9a36-428b-976e-bfeb438250ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>8e693966-aa61-4dce-a406-aa30ead4503d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4321c93c-a032-4572-a3b7-1446c06ff525</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>QA</value>
      <webElementGuid>af0e2b3f-eca5-4e78-bd55-28ce36662a70</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8a3153669274e41ebad021ae73d01630</value>
      <webElementGuid>f1fb6a55-b10a-4d40-abdb-f18a3a46e620</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(name() = 'li') and (position() = 112)]//*[@role = 'option']</value>
      <webElementGuid>d482b66a-fd0c-4beb-931d-8c2b9c01aed4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(name() = 'li') and (position() = 112)]//*[@role = 'option']</value>
      <webElementGuid>fc844278-f4ee-492d-a813-f47658f762f2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[(text() = 'QA' or . = 'QA')]</value>
      <webElementGuid>5b218e8b-93da-4c95-b72e-2805f1c790e7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
