<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btn_attachFromDevice</name>
   <tag></tag>
   <elementGuidId>1b79193d-1012-456f-8b5f-22b47a35ca79</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#myfile</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'myfile']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#myfile</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e0398881-67ec-4936-b61b-ee37c9ffb60b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>4cf711c4-acd0-4039-a36c-28efa0a96cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>myfile</value>
      <webElementGuid>46812e63-77d5-4a08-9a53-555c4648c1bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>file[]</value>
      <webElementGuid>36b9b27c-5641-4cd7-af4a-cb95e10823b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.jpg, .jpeg, .png, .pdf, .doc, .docx</value>
      <webElementGuid>bc57ce8a-e323-4cba-8cbf-4d7f5f6c9cd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gray-button</value>
      <webElementGuid>c11dfe6d-27c4-4450-9bc7-727dcd063f72</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-6fc3ea9d9af124d6835d76db8e70ad78</value>
      <webElementGuid>5cca6254-e73e-44c8-b3c6-e53ff133de39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'myfile']</value>
      <webElementGuid>e2261366-531e-4419-a99f-8cec4d7e93a9</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'myfile']</value>
      <webElementGuid>dee27e82-2c32-4200-ab28-232f246fc2f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'myfile' and @name = 'file[]']</value>
      <webElementGuid>2d742184-cefd-439e-b391-32f140154322</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
