<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>lnk_sendConversation</name>
   <tag></tag>
   <elementGuidId>81e49c83-fcd8-4e6e-985e-98e496b40506</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#send_conversation</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'send_conversation']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#send_conversation</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>1b0798e1-3424-4cf0-b34e-3cefcf7b1d6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>send_conversation</value>
      <webElementGuid>86f0eda9-d352-490a-8db5-1dae6be78d00</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wfm-c-button wfm-c-button--primary wfm-c-button--lg</value>
      <webElementGuid>941a0a2a-35f3-4047-ad6d-88cf57774214</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>dropdown</value>
      <webElementGuid>224f34ef-09c1-430e-8780-d8553416aa48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-haspopup</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>08769380-6d99-4854-be77-253f32977f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>21af0b71-e289-4145-a8ac-4dbb38f2e30b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                Yes
            </value>
      <webElementGuid>f51cedec-b9f9-4fd5-a7f9-95c3b7012dd5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-630d83140b064d300230fa764982ab9b</value>
      <webElementGuid>cd193868-074a-4000-8338-0a714b3fda0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'send_conversation']</value>
      <webElementGuid>8c19d423-2e0f-430f-bea3-15832590fb59</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'send_conversation']</value>
      <webElementGuid>cbb157a3-84ad-4f33-8959-4f7d8ca97841</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@id = 'send_conversation' and (text() = '
                Yes
            ' or . = '
                Yes
            ')]</value>
      <webElementGuid>8a6e333e-d512-40f3-985a-02e4d7d2cdbd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
