<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_iframe</name>
   <tag></tag>
   <elementGuidId>13e97f8e-fddc-47cf-b721-2213f362ed54</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'iframe']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#iframe</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Loading…&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>cbeb8449-0a18-4135-90df-d4e5c3743b59</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b60afb31-c09b-4ee0-8e25-42127077bc85</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://testgov.1gov.ng/webform/TEST%2520AUTOMATION%25205?tenantId=11088&amp;auth=aFRScnFjY3BLR0w3ajZyV0hyQ1kzZUZBMUFJaTVB&amp;accessToken=c219b652-4307-4ba6-a932-3a59c7631e3e</value>
      <webElementGuid>414efbbe-6129-4110-9254-b55aef60a2ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>edcc297d-0170-4dbb-80bc-992655ffc206</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1435</value>
      <webElementGuid>41789c8d-3709-4a58-8083-95d54a457741</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8aa36b7e-eaac-4546-aaf9-b51e072830bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>b4f0f8c0-08e5-4639-992e-10fa1df68a39</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>c55e2526-366b-4cb2-9443-bb6b4505c8b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>resizeIframe(this)</value>
      <webElementGuid>4bb6125b-3555-446a-b6bb-744e6d776031</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> 
        Loading…
      </value>
      <webElementGuid>855ba157-9c90-4c22-b9fa-4c09b8df6cbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-da9f8ce4846c8c7dbeb042ef74222714</value>
      <webElementGuid>c8928fa8-6695-4365-b525-b1550dad053e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'iframe']</value>
      <webElementGuid>8cc95721-4019-4dca-ac1a-99d1894d25d7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'iframe']</value>
      <webElementGuid>bc58e25b-f2a3-405e-9e68-0f238c33eac1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@id = 'iframe' and @src = 'https://testgov.1gov.ng/webform/TEST%2520AUTOMATION%25205?tenantId=11088&amp;auth=aFRScnFjY3BLR0w3ajZyV0hyQ1kzZUZBMUFJaTVB&amp;accessToken=c219b652-4307-4ba6-a932-3a59c7631e3e' and (text() = ' 
        Loading…
      ' or . = ' 
        Loading…
      ')]</value>
      <webElementGuid>6b3574cb-565d-418a-8717-fbcef7a6c949</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
