<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_contact.fields.first_name</name>
   <tag></tag>
   <elementGuidId>c015c9d7-ce81-46c6-9557-5bdb144de963</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'contact.fields.first_name']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;contact\.fields\.first_name&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;contact\.fields\.first_name&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>db81a473-dc16-4577-9dfc-31a1950dca49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextField_input__-8eep</value>
      <webElementGuid>86a503d4-2ac7-4c72-8f56-3a17de0b57b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contact.fields.first_name</value>
      <webElementGuid>6dcb8ea2-1891-4a71-a04f-382679806601</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>04660899-b963-4d71-8ff0-aee13f00181c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-6eb83617763423125907efbe70124b11</value>
      <webElementGuid>46c4c2f7-f56e-459f-bae8-279806a2098e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'contact.fields.first_name']</value>
      <webElementGuid>29e64056-4dd5-4a25-a594-0e75710dec29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Pages_NEW/WorkOrder_View/Page_Web Form  Internal- Workforce Manager/iframe_iframe</value>
      <webElementGuid>8d039cbf-e3c5-4ecc-a69d-cce2b2ada125</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'contact.fields.first_name']</value>
      <webElementGuid>cf30752d-0fe3-4521-b0f5-757001a68c49</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'contact.fields.first_name' and @type = 'input']</value>
      <webElementGuid>dd6c8395-74a5-4769-a4ca-a107053d1877</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
