<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_contact.fields.title</name>
   <tag></tag>
   <elementGuidId>c966e2c6-2fee-413c-bf84-0fa321064e96</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'contact.fields.title']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;contact\.fields\.title&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;contact\.fields\.title&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d112bda3-1616-41e7-9dba-1452b7b569e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextField_input__-8eep</value>
      <webElementGuid>9b95465b-ad84-4e1d-ae12-4afbf9771a9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>contact.fields.title</value>
      <webElementGuid>87270dce-7bbb-4d65-977a-5d784a9f06d7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>20a4f36f-2211-4e9e-a9a5-2f25e94889d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-04da3e0167fefe6a4ee6103a6e3e7946</value>
      <webElementGuid>053669e7-eddd-485f-84b4-5b5c8f1d5dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'contact.fields.title']</value>
      <webElementGuid>4443afd5-ecef-4d54-a751-24b5bc266878</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Pages_NEW/WorkOrder_View/Page_Web Form  Internal- Workforce Manager/iframe_iframe</value>
      <webElementGuid>51e91569-2f6f-4d73-862f-2e57a70b8799</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'contact.fields.title']</value>
      <webElementGuid>fcfc4991-4487-467a-99a9-4c4db76a57b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'contact.fields.title' and @type = 'input']</value>
      <webElementGuid>a701acef-f2a1-44ad-9619-2d601051acc9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
