<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_organization.fields.address_line_2</name>
   <tag></tag>
   <elementGuidId>33357ab6-7643-46ba-a543-744a8840dfc3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'organization.fields.address_line_2']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;organization\.fields\.address_line_2&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;organization\.fields\.address_line_2&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>42d6391b-88af-4f76-aed3-ac1377f3254f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextField_input__-8eep</value>
      <webElementGuid>b606b4b5-d4da-4e0d-988a-08aab7ae9d17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>organization.fields.address_line_2</value>
      <webElementGuid>216db2d2-e781-4f18-9326-1a22d8c9a4e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a5474301-c6be-400d-a12e-a5190631c06b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-fc92331355cdd1051817a72df22c2009</value>
      <webElementGuid>95bfe68e-303a-4efd-ac9f-4eef18f2f5ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'organization.fields.address_line_2']</value>
      <webElementGuid>baf8b618-3666-47d2-95c5-2bd89a3ae9e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Pages_NEW/WorkOrder_View/Page_Web Form  Internal- Workforce Manager/iframe_iframe</value>
      <webElementGuid>a9a56465-5c0b-4e44-802d-d3166cff14d4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'organization.fields.address_line_2']</value>
      <webElementGuid>df5dbfb8-3efb-404c-9bee-e7cce5999041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'organization.fields.address_line_2' and @type = 'input']</value>
      <webElementGuid>e2c513b1-06bc-4dc5-9a5c-08586da0788d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
