<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_organization.fields.name_of_organaization</name>
   <tag></tag>
   <elementGuidId>7815ac8a-1866-42fd-9357-48b7c230224a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@name = 'organization.fields.name_of_organaization']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[name=&quot;organization\.fields\.name_of_organaization&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input[name=&quot;organization\.fields\.name_of_organaization&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>effd144d-5cb3-4e06-8fc4-818e4b2c8ca4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>TextField_input__-8eep</value>
      <webElementGuid>f7acb004-8098-4510-8db1-98f4a78accfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>organization.fields.name_of_organaization</value>
      <webElementGuid>0b1d5ce1-ae32-4351-8421-31d23a2964d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>6e817039-2926-40cd-92d3-3088a059bd5b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-de46232935c2a50d75b5b9e0b0c9d6d0</value>
      <webElementGuid>774cbd6f-3ebd-4b9e-8b2d-c0a08e7135d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@name = 'organization.fields.name_of_organaization']</value>
      <webElementGuid>b3515ecb-acd6-4945-baa4-82e075166ef9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Pages_NEW/WorkOrder_View/Page_Web Form  Internal- Workforce Manager/iframe_iframe</value>
      <webElementGuid>0925d26b-f25e-4e13-83da-32ad2aa03a55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@name = 'organization.fields.name_of_organaization']</value>
      <webElementGuid>3e1a823d-4324-459d-9df9-28bbb0584d7a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'organization.fields.name_of_organaization' and @type = 'input']</value>
      <webElementGuid>11b60f0b-a016-4e57-9bda-defc716645d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
