<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_img</name>
   <tag></tag>
   <elementGuidId>98a5a27b-bdbc-4fed-8ea1-0e8724ca95a6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@alt = '']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[alt=&quot;&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>df9fcb90-d9b6-4117-872f-d370c6dd819e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>612870b8-4f96-47b7-834a-55fff796d24a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>44</value>
      <webElementGuid>f3437586-fda9-484d-b132-b0181d86a00b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>38</value>
      <webElementGuid>bdcc36c4-3eac-4855-bc04-6b7351066417</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>829fca87-e055-423c-8624-01c8d65e93d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>5ad9c42e-36fc-48fc-b7b5-effc664a5aad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fsee_password_icon.4e981ef1.png&amp;w=48&amp;q=75 1x, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fsee_password_icon.4e981ef1.png&amp;w=96&amp;q=75 2x</value>
      <webElementGuid>580064be-5e89-4999-a066-f28ee7ad7016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fsee_password_icon.4e981ef1.png&amp;w=96&amp;q=75</value>
      <webElementGuid>3d81e203-40e1-4a5c-ba16-d05b63130f11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8e784fc2ac611eab664c834985d9984c</value>
      <webElementGuid>c75e244a-fff1-451d-ab81-755cb3490e88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@alt = '']</value>
      <webElementGuid>8ea70412-1844-498a-8d54-de9217d45708</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@alt = '']</value>
      <webElementGuid>e77bb802-ee2d-44f6-be5c-a74ebd44f64f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fsee_password_icon.4e981ef1.png&amp;w=96&amp;q=75']</value>
      <webElementGuid>0a7d01f7-7973-4191-854a-b1c381bd1c44</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
