<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_cde-widget</name>
   <tag></tag>
   <elementGuidId>7df337b6-7ea8-4ece-a009-2ff21f66f7e3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cde-widget</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'cde-widget']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>iframe[name=&quot;cde-widget&quot;]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>b282e47c-5302-491f-aa22-1ad23057968f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://govtest.convergenceondemand.com/cde/ecms-cde</value>
      <webElementGuid>633aa822-f954-4a78-8425-7d852464d9f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cde-widget</value>
      <webElementGuid>e967231e-ec26-4945-ae80-d7fdb05cb58c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cde-widget</value>
      <webElementGuid>707ba47d-a064-4f3b-ad05-eef999136e87</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>8b9d0bd0-81da-4839-88be-effbac52b1bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>allowtransparency</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>ddfafd98-3da6-4519-b236-a745fa3ff5a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-7f794dca172a3c8d0763ed83bc5d9711</value>
      <webElementGuid>6d176ab8-ce7c-4219-8167-9535f90837e3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'cde-widget']</value>
      <webElementGuid>b5cfaab7-3e25-41df-a7ae-4732e84becb1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'cde-widget']</value>
      <webElementGuid>cf41a0a3-13c0-4114-bfb6-987e882ce511</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@src = 'https://govtest.convergenceondemand.com/cde/ecms-cde' and @id = 'cde-widget' and @name = 'cde-widget']</value>
      <webElementGuid>e08990d6-1767-41b7-9619-a783ebb57ef5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
