<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_From Device</name>
   <tag></tag>
   <elementGuidId>6c53cd7d-8b8d-412b-97bd-8ee0fc14cc2b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#file_upload</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'file_upload']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Upload File&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>20a4ef34-5a73-4aaf-ab0d-6a489718fb6e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>0f289d50-aa99-46bb-b566-474785059e4e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onchange</name>
      <type>Main</type>
      <value>handleWorkOrderAttach(this.id)</value>
      <webElementGuid>d2fad937-cadd-4d88-b86f-c43f3b9f77a7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>file_upload</value>
      <webElementGuid>62a70702-623e-42ed-a790-5fe1d75861ed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-18e7b3886de2606066c70d2110aeb4ed</value>
      <webElementGuid>c7ceff99-8422-4212-a1c2-1e394f04df69</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'file_upload']</value>
      <webElementGuid>af67c5e8-cce3-44b6-afa6-cd5ba241ddfc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'file_upload']</value>
      <webElementGuid>ce86c0ff-cf6c-4044-ac73-20bde247b89e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'file_upload']</value>
      <webElementGuid>0d85c04e-baf7-405c-8246-8ab385985df8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
