<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_form-upload_input</name>
   <tag></tag>
   <elementGuidId>c3e76899-def9-4b22-9c17-c4fa149ded63</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'form-upload__input']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#form-upload__input</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#form-upload__input</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>06ec275d-4e6f-482c-b1bd-7d464c568e75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>file</value>
      <webElementGuid>1dee6d9d-d988-43e0-87fc-a6dc047c44d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-upload__input</value>
      <webElementGuid>290cf50e-d1e1-4c8d-a6fe-5c035704698b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>form-upload__input</value>
      <webElementGuid>ecfabaeb-cad7-42b8-8e57-2d6011496038</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>accept</name>
      <type>Main</type>
      <value>.png,.gif,.jpeg,.jpg</value>
      <webElementGuid>3f40b226-3c61-4017-a249-6f7ac273f047</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>enctype</name>
      <type>Main</type>
      <value>multipart/form-data</value>
      <webElementGuid>e0393665-7282-470f-bfa1-01c96079fd99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-cdc69b107115bbe5395c81090ca8dfe2</value>
      <webElementGuid>e1b62ba4-903f-4a3e-ae6b-48d63839f5b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'form-upload__input']</value>
      <webElementGuid>37ff1767-6d7e-4c7f-be36-320ae799e109</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'form-upload__input']</value>
      <webElementGuid>7e0b9767-68f5-43de-9ab5-6a3f2b1fe651</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'file' and @id = 'form-upload__input']</value>
      <webElementGuid>d2e72f78-8058-44dd-9181-3c8d659556af</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
