<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Update</name>
   <tag></tag>
   <elementGuidId>34c04b9d-3399-4e99-9750-d709590e0ba8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.wfm-c-button--primary.wfm-c-button--lg[type=&quot;submit&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' wfm-c-button--primary ') and contains(concat(' ', normalize-space(@class), ' '), ' wfm-c-button--lg ') and (@type = 'submit')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button[name=&quot;Update&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>b44757eb-ed28-4bea-9024-fbd5a5444713</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>4c4a0a26-36b6-42f1-9e63-680b721e1941</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>wfm-c-button wfm-c-button--primary wfm-c-button--lg</value>
      <webElementGuid>558140fc-aef5-438d-82fb-f81bb55a5b33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Update  </value>
      <webElementGuid>bd83b389-2c43-481a-a3ff-8f536bbd911a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-0c01dfbd5609d4a3d43691e50dd02a4d</value>
      <webElementGuid>2ac91dc7-8b5a-4fda-8c00-555a204b7f98</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' wfm-c-button--primary ') and contains(concat(' ', normalize-space(@class), ' '), ' wfm-c-button--lg ') and (@type = 'submit')]</value>
      <webElementGuid>e440bf00-4ded-43f8-9542-db5ece6fdc51</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@class and contains(concat(' ', normalize-space(@class), ' '), ' wfm-c-button--primary ') and contains(concat(' ', normalize-space(@class), ' '), ' wfm-c-button--lg ') and (@type = 'submit')]</value>
      <webElementGuid>30aa488a-8114-4bbc-88f9-805f4478a7ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and (text() = 'Update  ' or . = 'Update  ')]</value>
      <webElementGuid>34b145d1-578d-42e4-a64e-f3b03578b804</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
