<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Task Title _</name>
   <tag></tag>
   <elementGuidId>2be9d221-0e93-4766-b798-d959f2312933</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#WorkOrder_summary</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'WorkOrder_summary']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Task Title \n         \n        *&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>4134678a-c483-4fb0-8bb5-9a05f9f3fd35</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>60</value>
      <webElementGuid>2481437d-1124-4199-8a24-0c763d0fadea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>500</value>
      <webElementGuid>55ccda2a-80d0-414c-adcf-255abf322cfa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>22768735-b261-4c58-8351-9877d1be3a2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>summary</value>
      <webElementGuid>c667a249-92ca-437c-8605-2215248404be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>WorkOrder_summary</value>
      <webElementGuid>9e50eb87-61f4-448a-a5d4-30732e7996e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>c55a0cbb-f938-484e-83b2-0246c453c4e1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>861fe365-7fa2-4deb-88a4-2a0b10b5b68d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-3a0df69f496e2c1369253b20a4fd6753</value>
      <webElementGuid>f942ffb1-3361-4523-8868-f9d338d54462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'WorkOrder_summary']</value>
      <webElementGuid>67f46f9e-447f-4dec-9031-c00fcfa7260f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'WorkOrder_summary']</value>
      <webElementGuid>05837d8a-8943-474c-85b5-0a55ec34b64d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'summary' and @id = 'WorkOrder_summary' and @type = 'text']</value>
      <webElementGuid>56bec8ec-5f06-476b-83bb-73a6965802b9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
