<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Successful Please check your email for deta</name>
   <tag></tag>
   <elementGuidId>c49abb51-6bdd-46c4-b86b-330a47ccdfdf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[aria-live=&quot;polite&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-live = 'polite']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;Successful! Please check your email for details.&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>511429eb-a020-48d9-bb8b-63714b228af7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>5b7d0e0e-6d60-44be-a17e-d9f3e22a2ca0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>862deb05-2283-43aa-b439-b244f9f8f25b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>go3958317564</value>
      <webElementGuid>258f3c41-98de-4f94-9018-d3d673ee1a5d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Successful! Please check your email for details.</value>
      <webElementGuid>8ac82ec6-b539-4d10-a878-a231c82ed010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-16f25860536b1543d1285d59f5090c5f</value>
      <webElementGuid>2c67050c-a0f4-4ba7-927a-03fccb1eb6bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-live = 'polite']</value>
      <webElementGuid>112f4cfb-95dd-4dfc-811c-d087f9ecbf55</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-live = 'polite']</value>
      <webElementGuid>1bef4693-be87-4020-88ae-9a97bc005cf3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Successful! Please check your email for details.' or . = 'Successful! Please check your email for details.')]</value>
      <webElementGuid>a852bcc9-2f30-45bb-9125-8b18fa04ee9e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
