<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_FAILED_VALIDATION</name>
   <tag></tag>
   <elementGuidId>2451a560-b658-4fb8-b09a-e3b7ef1829d7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[(text() = 'FAILED_VALIDATION' or . = 'FAILED_VALIDATION')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[aria-live=&quot;polite&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@aria-live = 'polite']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:text=&quot;FAILED_VALIDATION&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>bdf4e275-7932-4d8d-a594-a42a71a4938b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>go3958317564</value>
      <webElementGuid>7f512711-5bda-473b-96ec-f7e98cd7074f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>FAILED_VALIDATION</value>
      <webElementGuid>ab00208b-5cc0-4b79-98bf-0956ac0fef66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-16f25860536b1543d1285d59f5090c5f</value>
      <webElementGuid>bfc90ca2-a16c-4556-bfe2-dc0026ac923c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@aria-live = 'polite']</value>
      <webElementGuid>822b984c-6f6e-45d2-92e2-129f2ddb5809</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>status</value>
      <webElementGuid>f539a2ef-9eb9-4d7a-bab6-c04f66fda8a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-live</name>
      <type>Main</type>
      <value>polite</value>
      <webElementGuid>998e04d8-db80-4844-b4bc-1ddc014156b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@aria-live = 'polite']</value>
      <webElementGuid>26ef0e38-72bd-40cb-8093-6661a3fdb698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'FAILED_VALIDATION' or . = 'FAILED_VALIDATION')]</value>
      <webElementGuid>d90e7904-eb12-4262-8118-25e2606b2d1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@data-rht-toaster = '']/div/div</value>
      <webElementGuid>1d1b5fdd-7604-4c57-a8d9-5eac940ba87f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'An OTP has been sent to your email.' or . = 'An OTP has been sent to your email.')]</value>
      <webElementGuid>5861f439-8e35-4263-8295-c8154f78d4c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
