<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_img</name>
   <tag></tag>
   <elementGuidId>5d952ead-9eab-4edb-93b8-f8577e7c8f26</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@alt = '']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[alt=&quot;&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=button >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>b0f2de13-d750-4960-a303-0eead980d4de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>loading</name>
      <type>Main</type>
      <value>lazy</value>
      <webElementGuid>2139b05f-28b5-4b2b-a9b1-4054014b6082</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>44</value>
      <webElementGuid>f33e114a-b1d0-471c-9a0a-5e1ee4f6110d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>38</value>
      <webElementGuid>9a827ea0-85d0-4ebc-82d8-0d3c910e7cde</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>decoding</name>
      <type>Main</type>
      <value>async</value>
      <webElementGuid>86b92e9b-9125-4240-98c3-cab40340fc17</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-nimg</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>38404338-e776-4fe7-9600-4eceb6ac473e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>srcset</name>
      <type>Main</type>
      <value>/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fsee_password_icon.4e981ef1.png&amp;w=48&amp;q=75 1x, /_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fsee_password_icon.4e981ef1.png&amp;w=96&amp;q=75 2x</value>
      <webElementGuid>d4fd1c78-d09d-4c38-8887-6e6a3ef70ac9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fsee_password_icon.4e981ef1.png&amp;w=96&amp;q=75</value>
      <webElementGuid>1e681ef5-305e-42e6-8330-2014d6f63fe2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-8e784fc2ac611eab664c834985d9984c</value>
      <webElementGuid>d8c0abc9-5fa1-4e7d-b8b3-59de322945b2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@alt = '']</value>
      <webElementGuid>01e62cf4-c596-4612-b028-2b25b6ed748a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@alt = '']</value>
      <webElementGuid>df06167e-caca-4d3a-9000-8e80bd11beb7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '/_next/image?url=%2F_next%2Fstatic%2Fmedia%2Fsee_password_icon.4e981ef1.png&amp;w=96&amp;q=75']</value>
      <webElementGuid>a98b40a4-290a-4d87-bdc3-b0c646d5c975</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
