<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_focus_outline-none focus_ring-2 focus_ring_4</name>
   <tag></tag>
   <elementGuidId>5e9ccab1-8a17-423e-af1e-b016df6e065c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'tel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[value=&quot;&quot;]:nth-child(5)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[(@value = '') and (position() = 5)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input:nth-child(5)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>02b74c26-4210-492b-b9f0-b30b82e09bee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>4d754767-e68f-4875-acf0-d8807a153b71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>e3b3d5e9-842f-4180-a8c3-2606f7624872</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focus:outline-none focus:ring-2 focus:ring-green-500</value>
      <webElementGuid>007c9b1a-aaac-4eea-a6a8-465572e2d0ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>1ddec7fd-e191-453c-95d5-19be6bd215c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-35f87b69bc7b457e9704549c94f8f73a</value>
      <webElementGuid>1cb31ad9-1992-4dd6-84ef-40dea91d1133</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@value = '') and (position() = 5)]</value>
      <webElementGuid>84637465-aefd-47fc-91bf-76a9e6fbef4e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@value = '') and (position() = 5)]</value>
      <webElementGuid>480b60ba-025f-4c9c-9477-73838d08d2b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel']</value>
      <webElementGuid>219d399c-1d6d-4686-8c09-2cadac364caf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
