<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_focus_outline-none focus_ring-2 focus_ring_5</name>
   <tag></tag>
   <elementGuidId>fd2ec236-da26-4d70-a313-d126815b6f2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'tel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[type=&quot;tel&quot;]:nth-child(6)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[(@type = 'tel') and (position() = 6)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input:nth-child(6)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>89cda086-d1d5-41ae-a1db-5d00fd1dd7ba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>6006a857-39cc-4bf3-a097-eab18e5eb77b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f9098a5d-517a-4903-b9b9-1758ca64e8dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focus:outline-none focus:ring-2 focus:ring-green-500</value>
      <webElementGuid>1893ce4b-2000-4dc5-a7f6-6bc8a7339fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>0796b7a2-f99d-4fc2-ae4b-bebf31af6603</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>6</value>
      <webElementGuid>895700b4-37ea-479e-87fb-025772e4f11f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-bba49f74607a4343f7f4283bba1d81ba</value>
      <webElementGuid>7cb1d0b4-057b-4cdb-b298-db26f288f234</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@type = 'tel') and (position() = 6)]</value>
      <webElementGuid>31c26a20-71fd-431a-92d6-ad47fbc70899</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@type = 'tel') and (position() = 6)]</value>
      <webElementGuid>0d97e7c2-7044-4e16-a799-5066dc18d513</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel']</value>
      <webElementGuid>51bed2de-6e39-41ff-b742-b6963ce8b070</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@value = '') and (position() = 1)]</value>
      <webElementGuid>50fcc27c-ad12-4b1d-9aad-a711dfc268e0</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
