<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_GovOTP</name>
   <tag></tag>
   <elementGuidId>998a03b4-df2d-4d52-bcc2-396a86946c76</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>[value=&quot;AUTHENTICATOR_APP&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@value = 'AUTHENTICATOR_APP']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;GovOTP&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d00fdc3c-2874-490f-9d6d-cce026b5d789</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>accent-brand-green</value>
      <webElementGuid>023c59f6-d69f-495d-b91f-14cbe52780be</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>49926276-06b6-4c42-8970-9769e55ba989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>AUTHENTICATOR_APP</value>
      <webElementGuid>985b9802-2133-4e38-86f7-ba5dce91ce4b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>otpMethod</value>
      <webElementGuid>3f70d1fd-561a-4cdc-ac7b-14711dd5c4af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-32ff65169d2519c82561d8b4b97f0a7e</value>
      <webElementGuid>e45176c5-1ea2-4006-a4b9-a691e84e9360</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@value = 'AUTHENTICATOR_APP']</value>
      <webElementGuid>e89064e9-5c0e-44ca-ac5f-3fcf9102b618</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@value = 'AUTHENTICATOR_APP']</value>
      <webElementGuid>5b324d08-7f08-464f-8aab-0d85c1ac3d0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'otpMethod']</value>
      <webElementGuid>bcb7a7b0-ba82-492a-8bc5-0cde8064a108</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
