<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_focus_outline-none focus_ring-2 focus_ring_3</name>
   <tag></tag>
   <elementGuidId>78737c07-4b29-4cfe-af2f-86c73b9984c4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'tel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[value=&quot;&quot;]:nth-child(4)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[(@value = '') and (position() = 4)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>input:nth-child(4)</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f3eb0766-cb7c-4ff1-9fe6-61f9f08ca48c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>4963d8fc-0293-4dc0-9f61-d671b88ca7ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>de9dcc7f-ede6-44fe-9b57-bcc5f3526551</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focus:outline-none focus:ring-2 focus:ring-green-500</value>
      <webElementGuid>467769ac-eb5c-462e-99e3-d3352bfc241c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>87dd02e5-a3e2-4fae-9fd2-bd80c93eb8e4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-84d6fbf10908d882afc62117bba3e273</value>
      <webElementGuid>b40fb890-206c-4d0b-b367-e14d323336a0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@value = '') and (position() = 4)]</value>
      <webElementGuid>9c85f91d-ccbf-414d-9a09-ab98a2f5ea7f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@value = '') and (position() = 4)]</value>
      <webElementGuid>60f20e8c-a416-4d37-b3d8-c6c7432f960b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel']</value>
      <webElementGuid>1cf4dd36-5b19-4a31-99d2-7a901f1ec124</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
