<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_focus_outline-none focus_ring-2 focus_ring</name>
   <tag></tag>
   <elementGuidId>8fba3791-9182-43b7-b618-0fd6687234ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//*[@type = 'tel']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>[value=&quot;&quot;]:nth-child(1)</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[(@value = '') and (position() = 1)]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>.focus\:outline-none >> nth=0</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>67a6ee8b-c395-4fb2-8a1a-4cc837573424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>inputmode</name>
      <type>Main</type>
      <value>numeric</value>
      <webElementGuid>96946545-7c73-44ab-aaf0-fc4066cfd4c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>204a9ff6-9bf6-4052-b3d8-ae8d75f0f984</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>focus:outline-none focus:ring-2 focus:ring-green-500</value>
      <webElementGuid>67eabb93-20bc-49d3-98cb-677e04027016</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>tel</value>
      <webElementGuid>e964229b-1121-43ce-bd61-14e03fccb1d9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-049e895e547862dfb45b49dd836a0a0c</value>
      <webElementGuid>8632246d-dac1-4c34-b121-4fe8a537fbab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[(@value = '') and (position() = 1)]</value>
      <webElementGuid>a7e4622d-c533-46fb-b722-15846b2bd757</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[(@value = '') and (position() = 1)]</value>
      <webElementGuid>99f82a0d-f88b-41cc-bcf6-ca35afd30532</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'tel']</value>
      <webElementGuid>db9192d3-273e-486d-8b8f-dd3924867d06</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
